
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action DonateAction;
	
	private global::Gtk.Action helpAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action ParkitectFolderAction;
	
	private global::Gtk.Action ConfigAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.EventBox LoginBox;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Image image71;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Alignment alignment4;
	
	private global::Gtk.Image ParkitectnexusLogo;
	
	private global::Gtk.Notebook Pages;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Alignment alignment2;
	
	private global::Gtk.Button btnLaunchParkitect;
	
	private global::Gtk.Statusbar LoadingStatus;
	
	private global::Gtk.Label TaskInfoField;
	
	private global::Gtk.ProgressBar StatusLoading;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.DonateAction = new global::Gtk.Action ("DonateAction", global::Mono.Unix.Catalog.GetString ("Donate"), null, null);
		this.DonateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Donate");
		w1.Add (this.DonateAction, null);
		this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-help");
		this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.helpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.ParkitectFolderAction = new global::Gtk.Action ("ParkitectFolderAction", global::Mono.Unix.Catalog.GetString ("Parkitect folder"), null, null);
		this.ParkitectFolderAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Parkitect folder");
		w1.Add (this.ParkitectFolderAction, null);
		this.ConfigAction = new global::Gtk.Action ("ConfigAction", global::Mono.Unix.Catalog.GetString ("Config"), null, null);
		this.ConfigAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Config");
		w1.Add (this.ConfigAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Parkitect Nexus");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitectnexus_logo.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='helpAction' action='helpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.hbox3.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.LoginBox = new global::Gtk.EventBox ();
		this.LoginBox.Name = "LoginBox";
		// Container child LoginBox.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.image71 = new global::Gtk.Image ();
		this.image71.Name = "image71";
		this.image71.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
		this.hbox4.Add (this.image71);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image71]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("User");
		this.hbox4.Add (this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.LoginBox.Add (this.hbox4);
		this.hbox3.Add (this.LoginBox);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LoginBox]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		this.alignment4.LeftPadding = ((uint)(10));
		this.alignment4.TopPadding = ((uint)(5));
		// Container child alignment4.Gtk.Container+ContainerChild
		this.ParkitectnexusLogo = new global::Gtk.Image ();
		this.ParkitectnexusLogo.Name = "ParkitectnexusLogo";
		this.ParkitectnexusLogo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitectnexus_logo_full.png");
		this.alignment4.Add (this.ParkitectnexusLogo);
		this.hbox2.Add (this.alignment4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment4]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Pages = new global::Gtk.Notebook ();
		this.Pages.CanFocus = true;
		this.Pages.Name = "Pages";
		this.Pages.CurrentPage = 0;
		this.Pages.BorderWidth = ((uint)(3));
		// Notebook tab
		global::Gtk.Label w11 = new global::Gtk.Label ();
		w11.Visible = true;
		this.Pages.Add (w11);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Mods");
		this.Pages.SetTabLabel (w11, this.label4);
		this.label4.ShowAll ();
		this.vbox1.Add (this.Pages);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Pages]));
		w12.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.hbox1.Add (this.alignment2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment2]));
		w13.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnLaunchParkitect = new global::Gtk.Button ();
		this.btnLaunchParkitect.WidthRequest = 97;
		this.btnLaunchParkitect.HeightRequest = 34;
		this.btnLaunchParkitect.CanFocus = true;
		this.btnLaunchParkitect.Name = "btnLaunchParkitect";
		this.btnLaunchParkitect.UseUnderline = true;
		this.btnLaunchParkitect.Relief = ((global::Gtk.ReliefStyle)(1));
		global::Gtk.Image w14 = new global::Gtk.Image ();
		w14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitect_logo.png");
		this.btnLaunchParkitect.Image = w14;
		this.hbox1.Add (this.btnLaunchParkitect);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnLaunchParkitect]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		w15.Padding = ((uint)(5));
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w16.Position = 3;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.LoadingStatus = new global::Gtk.Statusbar ();
		this.LoadingStatus.Name = "LoadingStatus";
		this.LoadingStatus.Spacing = 2;
		// Container child LoadingStatus.Gtk.Box+BoxChild
		this.TaskInfoField = new global::Gtk.Label ();
		this.TaskInfoField.Name = "TaskInfoField";
		this.TaskInfoField.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
		this.LoadingStatus.Add (this.TaskInfoField);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.LoadingStatus [this.TaskInfoField]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child LoadingStatus.Gtk.Box+BoxChild
		this.StatusLoading = new global::Gtk.ProgressBar ();
		this.StatusLoading.Name = "StatusLoading";
		this.StatusLoading.Fraction = 0.07;
		this.StatusLoading.Ellipsize = ((global::Pango.EllipsizeMode)(2));
		this.LoadingStatus.Add (this.StatusLoading);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.LoadingStatus [this.StatusLoading]));
		w18.Position = 1;
		this.vbox1.Add (this.LoadingStatus);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.LoadingStatus]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 460;
		this.DefaultHeight = 455;
		this.StatusLoading.Hide ();
		this.LoadingStatus.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AboutAction.Activated += new global::System.EventHandler (this.AboutDialog);
	}
}
