
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action DonateAction;
	
	private global::Gtk.Action helpAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action ParkitectFolderAction;
	
	private global::Gtk.Action ConfigAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Alignment alignment1;
	
	private global::Gtk.EventBox LoginBox;
	
	private global::Gtk.HBox LoginContainer;
	
	private global::Gtk.Image LoginIcon;
	
	private global::Gtk.Label LoginLabel;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Alignment alignment4;
	
	private global::Gtk.Image ParkitectnexusLogo;
	
	private global::Gtk.Notebook Pages;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Alignment alignment2;
	
	private global::Gtk.Button btnLaunchParkitect;
	
	private global::Gtk.Statusbar LoadingStatus;
	
	private global::Gtk.Label TaskInfoField;
	
	private global::Gtk.ProgressBar StatusLoading;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.DonateAction = new global::Gtk.Action ("DonateAction", global::Mono.Unix.Catalog.GetString ("Donate"), null, null);
		this.DonateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Donate");
		w1.Add (this.DonateAction, null);
		this.helpAction = new global::Gtk.Action ("helpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-help");
		this.helpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.helpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.ParkitectFolderAction = new global::Gtk.Action ("ParkitectFolderAction", global::Mono.Unix.Catalog.GetString ("Parkitect folder"), null, null);
		this.ParkitectFolderAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Parkitect folder");
		w1.Add (this.ParkitectFolderAction, null);
		this.ConfigAction = new global::Gtk.Action ("ConfigAction", global::Mono.Unix.Catalog.GetString ("Config"), null, null);
		this.ConfigAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Config");
		w1.Add (this.ConfigAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Parkitect Nexus");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitectnexus_logo.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='helpAction' action='helpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.hbox3.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.hbox3.Add (this.alignment1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.alignment1]));
		w3.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.LoginBox = new global::Gtk.EventBox ();
		this.LoginBox.Name = "LoginBox";
		// Container child LoginBox.Gtk.Container+ContainerChild
		this.LoginContainer = new global::Gtk.HBox ();
		this.LoginContainer.Name = "LoginContainer";
		this.LoginContainer.Spacing = 1;
		// Container child LoginContainer.Gtk.Box+BoxChild
		this.LoginIcon = new global::Gtk.Image ();
		this.LoginIcon.Name = "LoginIcon";
		this.LoginIcon.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.user_icon_small.png");
		this.LoginContainer.Add (this.LoginIcon);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.LoginContainer [this.LoginIcon]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child LoginContainer.Gtk.Box+BoxChild
		this.LoginLabel = new global::Gtk.Label ();
		this.LoginLabel.Name = "LoginLabel";
		this.LoginLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Log In");
		this.LoginLabel.WidthChars = 9;
		this.LoginContainer.Add (this.LoginLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.LoginContainer [this.LoginLabel]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		this.LoginBox.Add (this.LoginContainer);
		this.hbox3.Add (this.LoginBox);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LoginBox]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment4.Name = "alignment4";
		this.alignment4.LeftPadding = ((uint)(10));
		this.alignment4.TopPadding = ((uint)(5));
		// Container child alignment4.Gtk.Container+ContainerChild
		this.ParkitectnexusLogo = new global::Gtk.Image ();
		this.ParkitectnexusLogo.Name = "ParkitectnexusLogo";
		this.ParkitectnexusLogo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitectnexus_logo_full.png");
		this.alignment4.Add (this.ParkitectnexusLogo);
		this.hbox2.Add (this.alignment4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment4]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Pages = new global::Gtk.Notebook ();
		this.Pages.CanFocus = true;
		this.Pages.Name = "Pages";
		this.Pages.CurrentPage = 0;
		this.Pages.BorderWidth = ((uint)(3));
		// Notebook tab
		global::Gtk.Label w12 = new global::Gtk.Label ();
		w12.Visible = true;
		this.Pages.Add (w12);
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Mods");
		this.Pages.SetTabLabel (w12, this.label4);
		this.label4.ShowAll ();
		this.vbox1.Add (this.Pages);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Pages]));
		w13.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.hbox1.Add (this.alignment2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment2]));
		w14.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnLaunchParkitect = new global::Gtk.Button ();
		this.btnLaunchParkitect.WidthRequest = 97;
		this.btnLaunchParkitect.HeightRequest = 34;
		this.btnLaunchParkitect.CanFocus = true;
		this.btnLaunchParkitect.Name = "btnLaunchParkitect";
		this.btnLaunchParkitect.UseUnderline = true;
		this.btnLaunchParkitect.Relief = ((global::Gtk.ReliefStyle)(1));
		global::Gtk.Image w15 = new global::Gtk.Image ();
		w15.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitect_logo.png");
		this.btnLaunchParkitect.Image = w15;
		this.hbox1.Add (this.btnLaunchParkitect);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnLaunchParkitect]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		w16.Padding = ((uint)(5));
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w17.Position = 3;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.LoadingStatus = new global::Gtk.Statusbar ();
		this.LoadingStatus.Name = "LoadingStatus";
		this.LoadingStatus.Spacing = 2;
		// Container child LoadingStatus.Gtk.Box+BoxChild
		this.TaskInfoField = new global::Gtk.Label ();
		this.TaskInfoField.Name = "TaskInfoField";
		this.TaskInfoField.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
		this.LoadingStatus.Add (this.TaskInfoField);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.LoadingStatus [this.TaskInfoField]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child LoadingStatus.Gtk.Box+BoxChild
		this.StatusLoading = new global::Gtk.ProgressBar ();
		this.StatusLoading.Name = "StatusLoading";
		this.StatusLoading.Fraction = 0.07;
		this.StatusLoading.Ellipsize = ((global::Pango.EllipsizeMode)(2));
		this.LoadingStatus.Add (this.StatusLoading);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.LoadingStatus [this.StatusLoading]));
		w19.Position = 1;
		this.vbox1.Add (this.LoadingStatus);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.LoadingStatus]));
		w20.Position = 4;
		w20.Expand = false;
		w20.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 583;
		this.DefaultHeight = 455;
		this.StatusLoading.Hide ();
		this.LoadingStatus.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AboutAction.Activated += new global::System.EventHandler (this.AboutDialog);
		this.LoginBox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.LoginButton);
		this.btnLaunchParkitect.Clicked += new global::System.EventHandler (this.LaunchParkitect);
	}
}
