
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
    private global::Gtk.VBox vbox1;
    
    private global::Gtk.HBox hbox2;
    
    private global::Gtk.Alignment alignment4;
    
    private global::Gtk.Image ParkitectnexusLogo;
    
    private global::Gtk.Notebook Pages;
    
    private global::Gtk.Label label4;
    
    private global::Gtk.HBox hbox1;
    
    private global::Gtk.Button btnLaunchParkitect;

    protected virtual void Build ()
    {
        global::Stetic.Gui.Initialize (this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
        this.WindowPosition = ((global::Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new global::Gtk.VBox ();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox2 = new global::Gtk.HBox ();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
        this.alignment4.Name = "alignment4";
        this.alignment4.LeftPadding = ((uint)(10));
        this.alignment4.TopPadding = ((uint)(5));
        // Container child alignment4.Gtk.Container+ContainerChild
        this.ParkitectnexusLogo = new global::Gtk.Image ();
        this.ParkitectnexusLogo.Name = "ParkitectnexusLogo";
        this.ParkitectnexusLogo.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitectnexus_logo_full.png");
        this.alignment4.Add (this.ParkitectnexusLogo);
        this.hbox2.Add (this.alignment4);
        global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment4]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        this.vbox1.Add (this.hbox2);
        global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.Pages = new global::Gtk.Notebook ();
        this.Pages.CanFocus = true;
        this.Pages.Name = "Pages";
        this.Pages.CurrentPage = 0;
        // Notebook tab
        global::Gtk.Label w4 = new global::Gtk.Label ();
        w4.Visible = true;
        this.Pages.Add (w4);
        this.label4 = new global::Gtk.Label ();
        this.label4.Name = "label4";
        this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
        this.Pages.SetTabLabel (w4, this.label4);
        this.label4.ShowAll ();
        this.vbox1.Add (this.Pages);
        global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Pages]));
        w5.Position = 1;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new global::Gtk.HBox ();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.btnLaunchParkitect = new global::Gtk.Button ();
        this.btnLaunchParkitect.CanFocus = true;
        this.btnLaunchParkitect.Name = "btnLaunchParkitect";
        this.btnLaunchParkitect.UseUnderline = true;
        this.btnLaunchParkitect.Label = global::Mono.Unix.Catalog.GetString ("Launch Parkitect");
        this.hbox1.Add (this.btnLaunchParkitect);
        global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnLaunchParkitect]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        this.vbox1.Add (this.hbox1);
        global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
        w7.Position = 2;
        w7.Expand = false;
        w7.Fill = false;
        this.Add (this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll ();
        }
        this.DefaultWidth = 460;
        this.DefaultHeight = 370;
        this.Show ();
        this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
        this.btnLaunchParkitect.Clicked += new global::System.EventHandler (this.LaunchParkitect);
    }
}
