
// This file has been generated by the GUI designer. Do not modify.
namespace ParkitectNexus.Client.Linux
{
	public partial class AboutDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image33;
		
		private global::Gtk.Notebook Pages;
		
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Button btnClose;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ParkitectNexus.Client.Linux.AboutDialog
			this.Name = "ParkitectNexus.Client.Linux.AboutDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child ParkitectNexus.Client.Linux.AboutDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image33 = new global::Gtk.Image ();
			this.image33.Name = "image33";
			this.image33.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.Linux.parkitectnexus_logo_full.png");
			this.hbox1.Add (this.image33);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image33]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.Pages = new global::Gtk.Notebook ();
			this.Pages.CanFocus = true;
			this.Pages.Name = "Pages";
			this.Pages.CurrentPage = 1;
			// Container child Pages.Gtk.Notebook+NotebookChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(15));
			this.alignment1.TopPadding = ((uint)(5));
			this.alignment1.RightPadding = ((uint)(5));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Parkitect Nexus Client\n\n(c) 2016, Tim Potze");
			this.vbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.alignment1.Add (this.vbox3);
			this.Pages.Add (this.alignment1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("About");
			this.Pages.SetTabLabel (this.alignment1, this.label1);
			this.label1.ShowAll ();
			// Notebook tab
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.Visible = true;
			this.Pages.Add (w7);
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Authors");
			this.Pages.SetTabLabel (w7, this.label4);
			this.label4.ShowAll ();
			this.vbox2.Add (this.Pages);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.Pages]));
			w8.Position = 1;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w9.Position = 0;
			// Internal child ParkitectNexus.Client.Linux.AboutDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnClose = new global::Gtk.Button ();
			this.btnClose.CanDefault = true;
			this.btnClose.CanFocus = true;
			this.btnClose.Name = "btnClose";
			this.btnClose.UseStock = true;
			this.btnClose.UseUnderline = true;
			this.btnClose.Label = "gtk-close";
			this.AddActionWidget (this.btnClose, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.btnClose]));
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 359;
			this.DefaultHeight = 200;
			this.Show ();
		}
	}
}
