
// This file has been generated by the GUI designer. Do not modify.
namespace ParkitectNexus.Client.GTK
{
    public partial class ParkitectUpdate
    {
        private global::Gtk.Alignment alignment2;
        
        private global::Gtk.Label updateInfo;
        
        private global::Gtk.Button btnCancel;
        
        private global::Gtk.Button btnOk;

        protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget ParkitectNexus.Client.GTK.ParkitectUpdate
            this.Name = "ParkitectNexus.Client.GTK.ParkitectUpdate";
            this.Title = global::Mono.Unix.Catalog.GetString ("ParkitectNexus Client");
            this.Icon = global::Gdk.Pixbuf.LoadFromResource ("ParkitectNexus.Client.GTK.nexus.ico");
            this.WindowPosition = ((global::Gtk.WindowPosition)(4));
            this.Resizable = false;
            // Internal child ParkitectNexus.Client.GTK.ParkitectUpdate.VBox
            global::Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
            this.alignment2.Name = "alignment2";
            w1.Add (this.alignment2);
            global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.alignment2]));
            w2.Position = 0;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.updateInfo = new global::Gtk.Label ();
            this.updateInfo.Name = "updateInfo";
            this.updateInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
            this.updateInfo.Wrap = true;
            w1.Add (this.updateInfo);
            global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.updateInfo]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Internal child ParkitectNexus.Client.GTK.ParkitectUpdate.ActionArea
            global::Gtk.HButtonBox w4 = this.ActionArea;
            w4.Name = "dialog1_ActionArea";
            w4.Spacing = 10;
            w4.BorderWidth = ((uint)(5));
            w4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnCancel = new global::Gtk.Button ();
            this.btnCancel.CanDefault = true;
            this.btnCancel.CanFocus = true;
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.UseStock = true;
            this.btnCancel.UseUnderline = true;
            this.btnCancel.Label = "gtk-cancel";
            this.AddActionWidget (this.btnCancel, -6);
            global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.btnCancel]));
            w5.Expand = false;
            w5.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.btnOk = new global::Gtk.Button ();
            this.btnOk.CanDefault = true;
            this.btnOk.CanFocus = true;
            this.btnOk.Name = "btnOk";
            this.btnOk.UseStock = true;
            this.btnOk.UseUnderline = true;
            this.btnOk.Label = "gtk-ok";
            this.AddActionWidget (this.btnOk, -5);
            global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.btnOk]));
            w6.Position = 1;
            w6.Expand = false;
            w6.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 190;
            this.Show ();
            this.btnCancel.Clicked += new global::System.EventHandler (this.Cancel);
            this.btnOk.Clicked += new global::System.EventHandler (this.ProceedToUpdate);
        }
    }
}
