
// This file has been generated by the GUI designer. Do not modify.
namespace ParkitectNexus.Client.GTK
{
    public partial class CheckableItems
    {
        private global::Gtk.HPaned hpaned3;
        
        private global::Gtk.CheckButton checkbutton2;

        protected virtual void Build ()
        {
            global::Stetic.Gui.Initialize (this);
            // Widget ParkitectNexus.Client.GTK.CheckableItems
            global::Stetic.BinContainer.Attach (this);
            this.Name = "ParkitectNexus.Client.GTK.CheckableItems";
            // Container child ParkitectNexus.Client.GTK.CheckableItems.Gtk.Container+ContainerChild
            this.hpaned3 = new global::Gtk.HPaned ();
            this.hpaned3.CanFocus = true;
            this.hpaned3.Name = "hpaned3";
            this.hpaned3.Position = 113;
            // Container child hpaned3.Gtk.Paned+PanedChild
            this.checkbutton2 = new global::Gtk.CheckButton ();
            this.checkbutton2.CanFocus = true;
            this.checkbutton2.Name = "checkbutton2";
            this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("checkbutton2");
            this.checkbutton2.Active = true;
            this.checkbutton2.DrawIndicator = true;
            this.checkbutton2.UseUnderline = true;
            this.hpaned3.Add (this.checkbutton2);
            global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned3 [this.checkbutton2]));
            w1.Resize = false;
            this.Add (this.hpaned3);
            if ((this.Child != null)) {
                this.Child.ShowAll ();
            }
            this.Hide ();
        }
    }
}
